import { Referral } from '@/types/referral';

export const mockReferralLogs: Referral[] = [
  {
    id: 'REF-2024-001',
    patient: {
      id: 'P001',
      fullName: 'John Doe',
      age: 45,
      sex: 'M',
      mrn: 'MRN12345',
      phone: '+251 911 223344',
    },
    vitals: {
      bp: '120/80',
      heartRate: 72,
      temperature: 36.5,
      respiratoryRate: 16,
      oxygenSaturation: 98,
    },
    reasonForReferral: 'Persistent chest pain and shortness of breath.',
    clinicalHistory: 'Patient has a history of hypertension...',
    provisionalDiagnosis: 'Unstable Angina',
    requiredSpecialty: 'Cardiology',
    status: 'pending',
    severity: 'high',
    severityScore: 8,
    referringHospital: 'Saint Paul Hospital',
    referringDoctor: 'Dr. Alice Smith',
    receivingHospital: 'Black Lion Specialized Hospital',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(), // 2 hours ago
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    comments: [],
  },
  {
    id: 'REF-2024-002',
    patient: {
      id: 'P002',
      fullName: 'Jane Smith',
      age: 28,
      sex: 'F',
      mrn: 'MRN67890',
      phone: '+251 922 334455',
    },
    vitals: {
      bp: '110/70',
      heartRate: 80,
      temperature: 37.2,
      respiratoryRate: 18,
      oxygenSaturation: 96,
    },
    reasonForReferral: 'Severe abdominal pain, suspected appendicitis.',
    clinicalHistory: 'Sudden onset of pain in the right lower quadrant...',
    provisionalDiagnosis: 'Acute Appendicitis',
    requiredSpecialty: 'General Surgery',
    status: 'approved',
    severity: 'critical',
    severityScore: 10,
    referringHospital: 'Saint Paul Hospital',
    referringDoctor: 'Dr. Bob Johnson',
    receivingHospital: 'Zewditu Memorial Hospital',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(), // 5 hours ago
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    comments: [],
  },
  {
    id: 'REF-2024-003',
    patient: {
      id: 'P003',
      fullName: 'Robert Wilson',
      age: 62,
      sex: 'M',
      mrn: 'MRN54321',
      phone: '+251 933 445566',
    },
    vitals: {
      bp: '140/90',
      heartRate: 65,
      temperature: 36.0,
      respiratoryRate: 14,
      oxygenSaturation: 94,
    },
    reasonForReferral: 'Blurred vision and frequent headaches.',
    clinicalHistory: 'Chronic diabetic patient for 10 years...',
    provisionalDiagnosis: 'Diabetic Retinopathy',
    requiredSpecialty: 'Ophthalmology',
    status: 'completed',
    severity: 'medium',
    severityScore: 5,
    referringHospital: 'Saint Paul Hospital',
    referringDoctor: 'Dr. Alice Smith',
    receivingHospital: 'Menelik II Referral Hospital',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    comments: [],
  },
  {
    id: 'REF-2024-004',
    patient: {
      id: 'P004',
      fullName: 'Maria Garcia',
      age: 35,
      sex: 'F',
      mrn: 'MRN98765',
      phone: '+251 944 556677',
    },
    vitals: {
      bp: '115/75',
      heartRate: 75,
      temperature: 38.5,
      respiratoryRate: 20,
      oxygenSaturation: 97,
    },
    reasonForReferral: 'High fever and persistent cough.',
    clinicalHistory: 'Fever for 3 days, non-responsive to paracetamol...',
    provisionalDiagnosis: 'Pneumonia',
    requiredSpecialty: 'Internal Medicine',
    status: 'rejected',
    severity: 'medium',
    severityScore: 6,
    referringHospital: 'Saint Paul Hospital',
    referringDoctor: 'Dr. Charlie Brown',
    receivingHospital: 'Tirunesh Beijing General Hospital',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(), // 3 days ago
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    comments: [],
  },
  {
    id: 'REF-2024-005',
    patient: {
      id: 'P005',
      fullName: 'Samuel Adebayo',
      age: 12,
      sex: 'M',
      mrn: 'MRN13579',
      phone: '+251 955 667788',
    },
    vitals: {
      bp: '100/60',
      heartRate: 90,
      temperature: 37.0,
      respiratoryRate: 22,
      oxygenSaturation: 99,
    },
    reasonForReferral: 'Recurring seizures.',
    clinicalHistory: 'First seizure at age 5...',
    provisionalDiagnosis: 'Epilepsy',
    requiredSpecialty: 'Pediatric Neurology',
    status: 'pending',
    severity: 'high',
    severityScore: 7,
    referringHospital: 'Saint Paul Hospital',
    referringDoctor: 'Dr. Diana Prince',
    receivingHospital: 'Yekatit 12 Medical College',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(), // 12 hours ago
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    comments: [],
  },
];
